-- Create weather_report database if it does not exist
CREATE DATABASE IF NOT EXISTS weather_db;
USE weather_db;

-- 1. Table for Current Weather (Location + Current)
CREATE TABLE IF NOT EXISTS current_weather (
    location_name VARCHAR(255) PRIMARY KEY,
    location_region VARCHAR(255),
    location_country VARCHAR(255),
    location_lat DECIMAL(9, 6),
    location_lon DECIMAL(9, 6),
    location_tz_id VARCHAR(100),
    location_localtime_epoch BIGINT,
    location_localtime DATETIME,
    current_last_updated_epoch BIGINT,
    current_last_updated DATETIME,
    current_temp_c DECIMAL(5, 2),
    current_temp_f DECIMAL(5, 2),
    current_is_day TINYINT,
    current_condition_text VARCHAR(255),
    current_condition_icon VARCHAR(255),
    current_condition_code INT,
    current_wind_mph DECIMAL(5, 2),
    current_wind_kph DECIMAL(5, 2),
    current_wind_degree INT,
    current_wind_dir VARCHAR(50),
    current_pressure_mb DECIMAL(6, 1),
    current_pressure_in DECIMAL(5, 2),
    current_precip_mm DECIMAL(6, 2),
    current_precip_in DECIMAL(5, 2),
    current_humidity INT,
    current_cloud INT,
    current_feelslike_c DECIMAL(5, 2),
    current_feelslike_f DECIMAL(5, 2),
    current_windchill_c DECIMAL(5, 2),
    current_windchill_f DECIMAL(5, 2),
    current_heatindex_c DECIMAL(5, 2),
    current_heatindex_f DECIMAL(5, 2),
    current_dewpoint_c DECIMAL(5, 2),
    current_dewpoint_f DECIMAL(5, 2),
    current_vis_km DECIMAL(5, 2),
    current_vis_miles DECIMAL(5, 2),
    current_uv DECIMAL(4, 1),
    current_gust_mph DECIMAL(5, 2),
    current_gust_kph DECIMAL(5, 2),
    current_will_it_rain TINYINT,
    current_chance_of_rain INT,
    current_will_it_snow TINYINT,
    current_chance_of_snow INT,
    current_short_rad DECIMAL(14, 2),
    current_diff_rad DECIMAL(14, 2),
    current_dni DECIMAL(14, 2),
    current_gti DECIMAL(14, 2),
    current_aqi_co DECIMAL(12, 6),
    current_aqi_no2 DECIMAL(12, 6),
    current_aqi_o3 DECIMAL(12, 6),
    current_aqi_so2 DECIMAL(12, 6),
    current_aqi_pm2_5 DECIMAL(12, 6),
    current_aqi_pm10 DECIMAL(12, 6),
    current_aqi_us_epa_index INT,
    current_aqi_gb_defra_index INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Table for Forecast Day (Location + Forecast Day + Astro)
CREATE TABLE IF NOT EXISTS forecast_day (
    location_name VARCHAR(255),
    location_region VARCHAR(255),
    location_country VARCHAR(255),
    location_lat DECIMAL(9, 6),
    location_lon DECIMAL(9, 6),
    location_tz_id VARCHAR(100),
    location_localtime_epoch BIGINT,
    location_localtime DATETIME,
    forecast_date DATE,
    forecast_date_epoch BIGINT,
    day_maxtemp_c DECIMAL(5, 2),
    day_maxtemp_f DECIMAL(5, 2),
    day_mintemp_c DECIMAL(5, 2),
    day_mintemp_f DECIMAL(5, 2),
    day_avgtemp_c DECIMAL(5, 2),
    day_avgtemp_f DECIMAL(5, 2),
    day_maxwind_mph DECIMAL(5, 2),
    day_maxwind_kph DECIMAL(5, 2),
    day_totalprecip_mm DECIMAL(6, 2),
    day_totalprecip_in DECIMAL(5, 2),
    day_totalsnow_cm DECIMAL(5, 2),
    day_avgvis_km DECIMAL(5, 2),
    day_avgvis_miles DECIMAL(5, 2),
    day_avghumidity INT,
    day_will_it_rain TINYINT,
    day_chance_of_rain INT,
    day_will_it_snow TINYINT,
    day_chance_of_snow INT,
    day_condition_text VARCHAR(255),
    day_condition_icon VARCHAR(255),
    day_condition_code INT,
    day_uv DECIMAL(4, 1),
    astro_sunrise VARCHAR(20),
    astro_sunset VARCHAR(20),
    astro_moonrise VARCHAR(20),
    astro_moonset VARCHAR(20),
    astro_moon_phase VARCHAR(50),
    astro_moon_illumination INT,
    astro_is_moon_up TINYINT,
    astro_is_sun_up TINYINT,
    day_aqi_co DECIMAL(12, 6),
    day_aqi_no2 DECIMAL(12, 6),
    day_aqi_o3 DECIMAL(12, 6),
    day_aqi_so2 DECIMAL(12, 6),
    day_aqi_pm2_5 DECIMAL(12, 6),
    day_aqi_pm10 DECIMAL(12, 6),
    day_aqi_us_epa_index INT,
    day_aqi_gb_defra_index INT,
    PRIMARY KEY (location_name, forecast_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Table for Forecast Hour (Location + Forecast Hour)
CREATE TABLE IF NOT EXISTS forecast_hour (
    location_name VARCHAR(255),
    location_region VARCHAR(255),
    location_country VARCHAR(255),
    location_lat DECIMAL(9, 6),
    location_lon DECIMAL(9, 6),
    location_tz_id VARCHAR(100),
    location_localtime_epoch BIGINT,
    location_localtime DATETIME,
    hour_time_epoch BIGINT,
    hour_time DATETIME,
    hour_temp_c DECIMAL(5, 2),
    hour_temp_f DECIMAL(5, 2),
    hour_is_day TINYINT,
    hour_condition_text VARCHAR(255),
    hour_condition_icon VARCHAR(255),
    hour_condition_code INT,
    hour_wind_mph DECIMAL(5, 2),
    hour_wind_kph DECIMAL(5, 2),
    hour_wind_degree INT,
    hour_wind_dir VARCHAR(50),
    hour_pressure_mb DECIMAL(6, 1),
    hour_pressure_in DECIMAL(5, 2),
    hour_precip_mm DECIMAL(6, 2),
    hour_precip_in DECIMAL(5, 2),
    hour_snow_cm DECIMAL(5, 2),
    hour_humidity INT,
    hour_cloud INT,
    hour_feelslike_c DECIMAL(5, 2),
    hour_feelslike_f DECIMAL(5, 2),
    hour_windchill_c DECIMAL(5, 2),
    hour_windchill_f DECIMAL(5, 2),
    hour_heatindex_c DECIMAL(5, 2),
    hour_heatindex_f DECIMAL(5, 2),
    hour_dewpoint_c DECIMAL(5, 2),
    hour_dewpoint_f DECIMAL(5, 2),
    hour_will_it_rain TINYINT,
    hour_chance_of_rain INT,
    hour_will_it_snow TINYINT,
    hour_chance_of_snow INT,
    hour_vis_km DECIMAL(5, 2),
    hour_vis_miles DECIMAL(5, 2),
    hour_gust_mph DECIMAL(5, 2),
    hour_gust_kph DECIMAL(5, 2),
    hour_uv DECIMAL(4, 1),
    hour_short_rad DECIMAL(14, 2),
    hour_diff_rad DECIMAL(14, 2),
    hour_dni DECIMAL(14, 2),
    hour_gti DECIMAL(14, 2),
    hour_aqi_co DECIMAL(12, 6),
    hour_aqi_no2 DECIMAL(12, 6),
    hour_aqi_o3 DECIMAL(12, 6),
    hour_aqi_so2 DECIMAL(12, 6),
    hour_aqi_pm2_5 DECIMAL(12, 6),
    hour_aqi_pm10 DECIMAL(12, 6),
    hour_aqi_us_epa_index INT,
    hour_aqi_gb_defra_index INT,
    PRIMARY KEY (location_name, hour_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Table for Master Report (All combined fields)
CREATE TABLE IF NOT EXISTS master_report (
    -- Location Fields
    location_name VARCHAR(255),
    location_region VARCHAR(255),
    location_country VARCHAR(255),
    location_lat DECIMAL(9, 6),
    location_lon DECIMAL(9, 6),
    location_tz_id VARCHAR(100),
    location_localtime_epoch BIGINT,
    location_localtime DATETIME,
    
    -- Current Fields
    current_last_updated_epoch BIGINT,
    current_last_updated DATETIME,
    current_temp_c DECIMAL(5, 2),
    current_temp_f DECIMAL(5, 2),
    current_is_day TINYINT,
    current_condition_text VARCHAR(255),
    current_condition_icon VARCHAR(255),
    current_condition_code INT,
    current_wind_mph DECIMAL(5, 2),
    current_wind_kph DECIMAL(5, 2),
    current_wind_degree INT,
    current_wind_dir VARCHAR(50),
    current_pressure_mb DECIMAL(6, 1),
    current_pressure_in DECIMAL(5, 2),
    current_precip_mm DECIMAL(6, 2),
    current_precip_in DECIMAL(5, 2),
    current_humidity INT,
    current_cloud INT,
    current_feelslike_c DECIMAL(5, 2),
    current_feelslike_f DECIMAL(5, 2),
    current_windchill_c DECIMAL(5, 2),
    current_windchill_f DECIMAL(5, 2),
    current_heatindex_c DECIMAL(5, 2),
    current_heatindex_f DECIMAL(5, 2),
    current_dewpoint_c DECIMAL(5, 2),
    current_dewpoint_f DECIMAL(5, 2),
    current_vis_km DECIMAL(5, 2),
    current_vis_miles DECIMAL(5, 2),
    current_uv DECIMAL(4, 1),
    current_gust_mph DECIMAL(5, 2),
    current_gust_kph DECIMAL(5, 2),
    current_will_it_rain TINYINT,
    current_chance_of_rain INT,
    current_will_it_snow TINYINT,
    current_chance_of_snow INT,
    current_short_rad DECIMAL(14, 2),
    current_diff_rad DECIMAL(14, 2),
    current_dni DECIMAL(14, 2),
    current_gti DECIMAL(14, 2),
    current_aqi_co DECIMAL(12, 6),
    current_aqi_no2 DECIMAL(12, 6),
    current_aqi_o3 DECIMAL(12, 6),
    current_aqi_so2 DECIMAL(12, 6),
    current_aqi_pm2_5 DECIMAL(12, 6),
    current_aqi_pm10 DECIMAL(12, 6),
    current_aqi_us_epa_index INT,
    current_aqi_gb_defra_index INT,

    -- Forecast Day / Astro Fields
    forecast_date DATE,
    forecast_date_epoch BIGINT,
    day_maxtemp_c DECIMAL(5, 2),
    day_maxtemp_f DECIMAL(5, 2),
    day_mintemp_c DECIMAL(5, 2),
    day_mintemp_f DECIMAL(5, 2),
    day_avgtemp_c DECIMAL(5, 2),
    day_avgtemp_f DECIMAL(5, 2),
    day_maxwind_mph DECIMAL(5, 2),
    day_maxwind_kph DECIMAL(5, 2),
    day_totalprecip_mm DECIMAL(6, 2),
    day_totalprecip_in DECIMAL(5, 2),
    day_totalsnow_cm DECIMAL(5, 2),
    day_avgvis_km DECIMAL(5, 2),
    day_avgvis_miles DECIMAL(5, 2),
    day_avghumidity INT,
    day_will_it_rain TINYINT,
    day_chance_of_rain INT,
    day_will_it_snow TINYINT,
    day_chance_of_snow INT,
    day_condition_text VARCHAR(255),
    day_condition_icon VARCHAR(255),
    day_condition_code INT,
    day_uv DECIMAL(4, 1),
    astro_sunrise VARCHAR(20),
    astro_sunset VARCHAR(20),
    astro_moonrise VARCHAR(20),
    astro_moonset VARCHAR(20),
    astro_moon_phase VARCHAR(50),
    astro_moon_illumination INT,
    astro_is_moon_up TINYINT,
    astro_is_sun_up TINYINT,
    day_aqi_co DECIMAL(12, 6),
    day_aqi_no2 DECIMAL(12, 6),
    day_aqi_o3 DECIMAL(12, 6),
    day_aqi_so2 DECIMAL(12, 6),
    day_aqi_pm2_5 DECIMAL(12, 6),
    day_aqi_pm10 DECIMAL(12, 6),
    day_aqi_us_epa_index INT,
    day_aqi_gb_defra_index INT,

    -- Forecast Hour Fields
    hour_time_epoch BIGINT,
    hour_time DATETIME,
    hour_temp_c DECIMAL(5, 2),
    hour_temp_f DECIMAL(5, 2),
    hour_is_day TINYINT,
    hour_condition_text VARCHAR(255),
    hour_condition_icon VARCHAR(255),
    hour_condition_code INT,
    hour_wind_mph DECIMAL(5, 2),
    hour_wind_kph DECIMAL(5, 2),
    hour_wind_degree INT,
    hour_wind_dir VARCHAR(50),
    hour_pressure_mb DECIMAL(6, 1),
    hour_pressure_in DECIMAL(5, 2),
    hour_precip_mm DECIMAL(6, 2),
    hour_precip_in DECIMAL(5, 2),
    hour_snow_cm DECIMAL(5, 2),
    hour_humidity INT,
    hour_cloud INT,
    hour_feelslike_c DECIMAL(5, 2),
    hour_feelslike_f DECIMAL(5, 2),
    hour_windchill_c DECIMAL(5, 2),
    hour_windchill_f DECIMAL(5, 2),
    hour_heatindex_c DECIMAL(5, 2),
    hour_heatindex_f DECIMAL(5, 2),
    hour_dewpoint_c DECIMAL(5, 2),
    hour_dewpoint_f DECIMAL(5, 2),
    hour_will_it_rain TINYINT,
    hour_chance_of_rain INT,
    hour_will_it_snow TINYINT,
    hour_chance_of_snow INT,
    hour_vis_km DECIMAL(5, 2),
    hour_vis_miles DECIMAL(5, 2),
    hour_gust_mph DECIMAL(5, 2),
    hour_gust_kph DECIMAL(5, 2),
    hour_uv DECIMAL(4, 1),
    hour_short_rad DECIMAL(14, 2),
    hour_diff_rad DECIMAL(14, 2),
    hour_dni DECIMAL(14, 2),
    hour_gti DECIMAL(14, 2),
    hour_aqi_co DECIMAL(12, 6),
    hour_aqi_no2 DECIMAL(12, 6),
    hour_aqi_o3 DECIMAL(12, 6),
    hour_aqi_so2 DECIMAL(12, 6),
    hour_aqi_pm2_5 DECIMAL(12, 6),
    hour_aqi_pm10 DECIMAL(12, 6),
    hour_aqi_us_epa_index INT,
    hour_aqi_gb_defra_index INT,
    PRIMARY KEY (location_name, forecast_date, hour_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
